name: Continuous integration
# attempt 2
on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
  schedule:
  - cron: 0 * * * *

env:
  RUSTFLAGS: -Dwarnings
  CARGO_INCREMENTAL: 0 # Speeds up the build (no cache) and reduces disk space!
  SCCACHE_CACHE_SIZE: 6G
  SCCACHE_DIR: ${{ github.workspace }}/.cache/sccache
  SCCACHE_ERROR_LOG: /tmp/sccache_log.txt
  SCCACHE_LOG: debug
  CARGO_INCREMENTAL: 0 # https://github.com/mozilla/sccache#rust

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v3
    - name: Setting up cache
      uses: pl-strflt/rust-sccache-action@v1
      env:
        SCCACHE_CACHE_SIZE: 6G
        SCCACHE_DIR: ${{ github.workspace }}/.cache/sccache
    - name: show cache
      run: |
        echo ${RUSTC_WRAPPER}
        echo ${SCCACHE_DIR}
        echo ${SCCACHE_CACHE_SIZE}
        echo $(ls ${{ github.workspace }}/.cache/sccache)
    - name: Running tests
      run: |
        export RUSTC_WRAPPER=sccache
        cargo test --locked --all --no-fail-fast --exclude=fil_builtin_actors_bundle
    - name: Show statistics
      run: |
        sccache --show-stats
    - name: Set summary
      if: (failure() || success())
      run: cat /tmp/sccache_log.txt >> $GITHUB_STEP_SUMMARY        
